### ISSUE TITLE
Static scan identified "Inadequate Encryption Strength"

### ISSUE THREAD

**Issue by dcowleyIDBS** [yajsw/yajsw#9]
In a recent static scan, the following flaw was identified

File: ServerCryptoFilterInbound.java: 85
Description: The key size specified for this algorithm is not large enough to protect it from brute force attacks.
Remediation: For Symmetric algorithms other than DES, use a key size >= 128bit, for RSA >= 2048bit, 3DES == 192 (168 effective).

The current key size is set to 512, and is recommended to be 1024 for RSA

**Comment by tananaev** [comment]
This is just a mirror of the official repository. Please file the ticket in the official repo.

**Comment by dcowleyIDBS** [comment]
Apologies.  Have raised the ticket on the official repo.  Thanks.
